// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TC.DataAccess.DatabaseContext;

namespace TC.DataAccess.Migrations
{
    [DbContext(typeof(TestingCenterDbContext))]
    [Migration("20191207031601_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TC.Entity.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Project","project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "system",
                            DateAdded = new DateTime(2019, 12, 6, 21, 16, 1, 389, DateTimeKind.Local).AddTicks(7287),
                            DateModified = new DateTime(2019, 12, 6, 21, 16, 1, 389, DateTimeKind.Local).AddTicks(7720),
                            Description = "",
                            IsActive = true,
                            ModifiedBy = "system",
                            Name = "Google"
                        });
                });

            modelBuilder.Entity("TC.Entity.Entities.ProjectDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectDomain","project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "system",
                            DateAdded = new DateTime(2019, 12, 6, 21, 16, 1, 390, DateTimeKind.Local).AddTicks(915),
                            DateModified = new DateTime(2019, 12, 6, 21, 16, 1, 390, DateTimeKind.Local).AddTicks(1309),
                            Domain = "google.com",
                            IsActive = true,
                            ModifiedBy = "system",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "system",
                            DateAdded = new DateTime(2019, 12, 6, 21, 16, 1, 390, DateTimeKind.Local).AddTicks(1944),
                            DateModified = new DateTime(2019, 12, 6, 21, 16, 1, 390, DateTimeKind.Local).AddTicks(1965),
                            Domain = "google.pl",
                            IsActive = true,
                            ModifiedBy = "system",
                            ProjectId = 1
                        });
                });

            modelBuilder.Entity("TC.Entity.Entities.TestInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("SeleniumCommands")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("TestInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "system",
                            DateAdded = new DateTime(2019, 12, 6, 21, 16, 1, 390, DateTimeKind.Local).AddTicks(6745),
                            DateModified = new DateTime(2019, 12, 6, 21, 16, 1, 390, DateTimeKind.Local).AddTicks(7139),
                            Description = "Using google search find c# tutorial",
                            IsActive = true,
                            ModifiedBy = "system",
                            Name = "Search for c# tutorial",
                            ProjectId = 1,
                            SeleniumCommands = "[{\"OperationId\":3,\"WebDriverOperationType\":0,\"Values\":[\"https://www.google.com\"]}]"
                        });
                });

            modelBuilder.Entity("TC.Entity.Entities.User.UserProjectStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProjectStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "system",
                            DateAdded = new DateTime(2019, 12, 6, 21, 16, 1, 386, DateTimeKind.Local).AddTicks(1097),
                            DateModified = new DateTime(2019, 12, 6, 21, 16, 1, 388, DateTimeKind.Local).AddTicks(3633),
                            IsActive = true,
                            ModifiedBy = "system",
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "system",
                            DateAdded = new DateTime(2019, 12, 6, 21, 16, 1, 388, DateTimeKind.Local).AddTicks(4175),
                            DateModified = new DateTime(2019, 12, 6, 21, 16, 1, 388, DateTimeKind.Local).AddTicks(4193),
                            IsActive = true,
                            ModifiedBy = "system",
                            Name = "Accepted"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "system",
                            DateAdded = new DateTime(2019, 12, 6, 21, 16, 1, 388, DateTimeKind.Local).AddTicks(4202),
                            DateModified = new DateTime(2019, 12, 6, 21, 16, 1, 388, DateTimeKind.Local).AddTicks(4205),
                            IsActive = true,
                            ModifiedBy = "system",
                            Name = "Rejected"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "system",
                            DateAdded = new DateTime(2019, 12, 6, 21, 16, 1, 388, DateTimeKind.Local).AddTicks(4207),
                            DateModified = new DateTime(2019, 12, 6, 21, 16, 1, 388, DateTimeKind.Local).AddTicks(4210),
                            IsActive = true,
                            ModifiedBy = "system",
                            Name = "Deleted"
                        });
                });

            modelBuilder.Entity("TC.Entity.Entities.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserGroup");
                });

            modelBuilder.Entity("TC.Entity.Entities.UserInGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("int");

                    b.Property<int>("UserModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserGroupId");

                    b.HasIndex("UserModelId");

                    b.ToTable("UserInGroup");
                });

            modelBuilder.Entity("TC.Entity.Entities.UserInProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserModelId")
                        .HasColumnType("int");

                    b.Property<int>("UserProjectStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserModelId");

                    b.HasIndex("UserProjectStatusId");

                    b.ToTable("UserInProject","user");
                });

            modelBuilder.Entity("TC.Entity.Entities.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserModel","user");
                });

            modelBuilder.Entity("TC.Entity.Entities.ProjectDomain", b =>
                {
                    b.HasOne("TC.Entity.Entities.Project", "Project")
                        .WithMany("ProjectDomains")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TC.Entity.Entities.TestInfo", b =>
                {
                    b.HasOne("TC.Entity.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TC.Entity.Entities.UserInGroup", b =>
                {
                    b.HasOne("TC.Entity.Entities.UserGroup", "UserGroup")
                        .WithMany("UserInGroup")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TC.Entity.Entities.UserModel", "UserModel")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TC.Entity.Entities.UserInProject", b =>
                {
                    b.HasOne("TC.Entity.Entities.Project", "Project")
                        .WithMany("UserInProject")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TC.Entity.Entities.UserModel", "UserModel")
                        .WithMany()
                        .HasForeignKey("UserModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TC.Entity.Entities.User.UserProjectStatus", "UserProjectStatus")
                        .WithMany()
                        .HasForeignKey("UserProjectStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
