name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    - name: Build with dotnet
      run: cd TC.WebService && dotnet build --configuration Release
    - name: Test with dotnet
      run: cd TC.WebServiceTest && dotnet test 
